apiVersion: v1
kind: Pod
metadata:
  name: test-pod
  namespace: staging
  labels:
    app: stage
spec:
  containers:
  - image: raftx/sample-web:v1
    name: stage-app
    resources:
      requests:
        cpu: "100m"
        memory: "256Mi"
      limits:
        cpu: "250m"
        memory: "512Mi"
